local effect_definitions = {
	{
		id = "thru",
		engine = "thru",
		label = "thru",
		params = { "tone", "gain" },
		param_count = 2,
		defaults = { amount = 0.0, param1 = 0.75, param2 = 0.5, param3 = 0.5, param4 = 0.5 },
	},
	{
		id = "low_pass",
		engine = "filter",
		label = "low pass",
		params = { "cutoff", "res", "mode", "slope" },
		param_count = 4,
		defaults = { amount = 1.0, param1 = 0.22, param2 = 0.48, param3 = 0.0, param4 = 1.0 },
	},
	{
		id = "band_pass",
		engine = "filter",
		label = "band pass",
		params = { "cutoff", "res", "mode", "slope" },
		param_count = 4,
		defaults = { amount = 1.0, param1 = 0.44, param2 = 0.82, param3 = 0.5, param4 = 1.0 },
	},
	{
		id = "high_pass",
		engine = "filter",
		label = "high pass",
		params = { "cutoff", "res", "mode", "slope" },
		param_count = 4,
		defaults = { amount = 1.0, param1 = 0.28, param2 = 0.42, param3 = 1.0, param4 = 1.0 },
	},
	{
		id = "muffled_bloom",
		engine = "filter",
		label = "muffled bloom",
		params = { "cutoff", "res", "mode", "slope" },
		param_count = 4,
		defaults = { amount = 0.82, param1 = 0.24, param2 = 0.42, param3 = 0.0, param4 = 1.0 },
	},
	{
		id = "radio_tunnel",
		engine = "filter",
		label = "radio tunnel",
		params = { "cutoff", "res", "mode", "slope" },
		param_count = 4,
		defaults = { amount = 0.84, param1 = 0.44, param2 = 0.74, param3 = 0.5, param4 = 1.0 },
	},
	{
		id = "airlift",
		engine = "filter",
		label = "airlift",
		params = { "cutoff", "res", "mode", "slope" },
		param_count = 4,
		defaults = { amount = 0.72, param1 = 0.62, param2 = 0.3, param3 = 1.0, param4 = 1.0 },
	},
	{
		id = "peak_sweep",
		engine = "filter",
		label = "peak sweep",
		params = { "cutoff", "res", "mode", "slope" },
		param_count = 4,
		defaults = { amount = 0.76, param1 = 0.58, param2 = 0.52, param3 = 0.5, param4 = 0.35 },
	},
	{
		id = "dark_shelf",
		engine = "filter",
		label = "dark shelf",
		params = { "cutoff", "res", "mode", "slope" },
		param_count = 4,
		defaults = { amount = 0.7, param1 = 0.18, param2 = 0.22, param3 = 0.0, param4 = 0.0 },
	},
	{
		id = "thin_ice",
		engine = "filter",
		label = "thin ice",
		params = { "cutoff", "res", "mode", "slope" },
		param_count = 4,
		defaults = { amount = 0.78, param1 = 0.74, param2 = 0.25, param3 = 1.0, param4 = 1.0 },
	},
	{
		id = "sub_cut",
		engine = "filter",
		label = "sub cut",
		params = { "cutoff", "res", "mode", "slope" },
		param_count = 4,
		defaults = { amount = 0.64, param1 = 0.14, param2 = 0.18, param3 = 1.0, param4 = 0.0 },
	},
	{
		id = "vowel_sweep",
		engine = "filter",
		label = "vowel sweep",
		params = { "cutoff", "res", "mode", "slope" },
		param_count = 4,
		defaults = { amount = 0.88, param1 = 0.5, param2 = 0.82, param3 = 0.5, param4 = 0.55 },
	},
	{
		id = "needle_focus",
		engine = "filter",
		label = "needle focus",
		params = { "cutoff", "res", "mode", "slope" },
		param_count = 4,
		defaults = { amount = 0.82, param1 = 0.68, param2 = 0.7, param3 = 0.5, param4 = 1.0 },
	},
	{
		id = "phaser",
		engine = "mod",
		label = "phaser",
		params = { "rate", "depth", "type", "stages" },
		param_count = 4,
		defaults = { amount = 0.55, param1 = 0.22, param2 = 0.42, param3 = 0.0, param4 = 0.58 },
	},
	{
		id = "flanger",
		engine = "mod",
		label = "flanger",
		params = { "rate", "depth", "type", "stages" },
		param_count = 4,
		defaults = { amount = 0.58, param1 = 0.28, param2 = 0.6, param3 = 0.5, param4 = 0.45 },
	},
	{
		id = "hollow_phase",
		engine = "mod",
		label = "hollow phase",
		params = { "rate", "depth", "type", "stages" },
		param_count = 4,
		defaults = { amount = 0.66, param1 = 0.16, param2 = 0.58, param3 = 0.0, param4 = 1.0 },
	},
	{
		id = "jet_wash",
		engine = "mod",
		label = "jet wash",
		params = { "rate", "depth", "type", "stages" },
		param_count = 4,
		defaults = { amount = 0.72, param1 = 0.24, param2 = 0.82, param3 = 0.5, param4 = 0.52 },
	},
	{
		id = "stereo_bloom",
		engine = "mod",
		label = "stereo bloom",
		params = { "rate", "depth", "type", "stages" },
		param_count = 4,
		defaults = { amount = 0.52, param1 = 0.18, param2 = 0.36, param3 = 1.0, param4 = 0.86 },
	},
	{
		id = "air_widen",
		engine = "space",
		label = "air widen",
		params = { "size", "damp", "type", "width" },
		param_count = 4,
		defaults = { amount = 0.36, param1 = 0.12, param2 = 0.18, param3 = 0.0, param4 = 0.95 },
	},
	{
		id = "washed_hall",
		engine = "space",
		label = "washed hall",
		params = { "size", "damp", "type", "width" },
		param_count = 4,
		defaults = { amount = 0.58, param1 = 0.72, param2 = 0.38, param3 = 1.0, param4 = 0.75 },
	},
	{
		id = "spring_tunnel",
		engine = "space",
		label = "spring tunnel",
		params = { "size", "damp", "type", "width" },
		param_count = 4,
		defaults = { amount = 0.55, param1 = 0.5, param2 = 0.35, param3 = 0.66, param4 = 0.35 },
	},
	{
		id = "burn_echo",
		engine = "delay",
		label = "burn echo",
		params = { "time", "feedback", "freeze", "tone" },
		param_count = 4,
		defaults = { amount = 0.62, param1 = 0.42, param2 = 0.62, param3 = 0.0, param4 = 0.3 },
	},
	{
		id = "compressor",
		engine = "texture",
		label = "compressor",
		params = { "color", "damage", "type", "motion" },
		param_count = 4,
		defaults = { amount = 0.46, param1 = 0.38, param2 = 0.36, param3 = 0.25, param4 = 0.2 },
	},
	{
		id = "limiter",
		engine = "texture",
		label = "limiter",
		params = { "color", "damage", "type", "motion" },
		param_count = 4,
		defaults = { amount = 0.58, param1 = 0.52, param2 = 0.18, param3 = 0.5, param4 = 0.0 },
	},
	{
		id = "glue_pump",
		engine = "texture",
		label = "glue pump",
		params = { "color", "damage", "type", "motion" },
		param_count = 4,
		defaults = { amount = 0.62, param1 = 0.34, param2 = 0.55, param3 = 0.25, param4 = 0.38 },
	},
	{
		id = "brick_squeeze",
		engine = "texture",
		label = "brick squeeze",
		params = { "color", "damage", "type", "motion" },
		param_count = 4,
		defaults = { amount = 0.78, param1 = 0.58, param2 = 0.16, param3 = 0.5, param4 = 0.0 },
	},
	{
		id = "crushed_bloom",
		engine = "texture",
		label = "crushed bloom",
		params = { "color", "damage", "type", "motion" },
		param_count = 4,
		defaults = { amount = 0.7, param1 = 0.4, param2 = 0.6, param3 = 0.75, param4 = 0.18 },
	},
	{
		id = "metal_gate",
		engine = "texture",
		label = "metal gate",
		params = { "color", "damage", "type", "motion" },
		param_count = 4,
		defaults = { amount = 0.66, param1 = 0.72, param2 = 0.46, param3 = 1.0, param4 = 0.52 },
	},
	{
		id = "broken_tape",
		engine = "texture",
		label = "broken tape",
		params = { "color", "damage", "type", "motion" },
		param_count = 4,
		defaults = { amount = 0.56, param1 = 0.28, param2 = 0.55, param3 = 0.75, param4 = 0.3 },
	},
	{
		id = "metal_room",
		engine = "texture",
		label = "metal room",
		params = { "color", "damage", "type", "motion" },
		param_count = 4,
		defaults = { amount = 0.52, param1 = 0.52, param2 = 0.48, param3 = 1.0, param4 = 0.4 },
	},
	{
		id = "karplus_bloom",
		engine = "resonator",
		label = "karplus bloom",
		params = { "tune", "decay", "body", "tone" },
		param_count = 4,
		defaults = { amount = 0.62, param1 = 0.24, param2 = 0.58, param3 = 0.48, param4 = 0.45 },
	},
	{
		id = "metal_string",
		engine = "resonator",
		label = "metal string",
		params = { "tune", "decay", "body", "tone" },
		param_count = 4,
		defaults = { amount = 0.72, param1 = 0.18, param2 = 0.74, param3 = 0.62, param4 = 0.3 },
	},
	{
		id = "folded_resonance",
		engine = "fold_filter",
		label = "folded resonance",
		params = { "cutoff", "res", "mode", "fold" },
		param_count = 4,
		defaults = { amount = 0.74, param1 = 0.42, param2 = 0.72, param3 = 0.5, param4 = 0.54 },
	},
	{
		id = "acid_fold",
		engine = "fold_filter",
		label = "acid fold",
		params = { "cutoff", "res", "mode", "fold" },
		param_count = 4,
		defaults = { amount = 0.82, param1 = 0.58, param2 = 0.88, param3 = 0.0, param4 = 0.78 },
	},
	{
		id = "vowel_formant",
		engine = "formant",
		label = "vowel formant",
		params = { "vowel", "spread", "focus", "tone" },
		param_count = 4,
		defaults = { amount = 0.64, param1 = 0.38, param2 = 0.42, param3 = 0.62, param4 = 0.55 },
	},
	{
		id = "choir_formant",
		engine = "formant",
		label = "choir formant",
		params = { "vowel", "spread", "focus", "tone" },
		param_count = 4,
		defaults = { amount = 0.72, param1 = 0.56, param2 = 0.58, param3 = 0.46, param4 = 0.7 },
	},
	{
		id = "plate_bright",
		engine = "plate",
		label = "plate bright",
		params = { "size", "decay", "pre", "tone" },
		param_count = 4,
		defaults = { amount = 0.58, param1 = 0.54, param2 = 0.48, param3 = 0.18, param4 = 0.82 },
	},
	{
		id = "plate_bloom",
		engine = "plate",
		label = "plate bloom",
		params = { "size", "decay", "pre", "tone" },
		param_count = 4,
		defaults = { amount = 0.74, param1 = 0.72, param2 = 0.66, param3 = 0.32, param4 = 0.58 },
	},
	{
		id = "early_bounce",
		engine = "early",
		label = "early bounce",
		params = { "size", "spread", "cluster", "tone" },
		param_count = 4,
		defaults = { amount = 0.52, param1 = 0.34, param2 = 0.48, param3 = 0.42, param4 = 0.72 },
	},
	{
		id = "room_slap",
		engine = "early",
		label = "room slap",
		params = { "size", "spread", "cluster", "tone" },
		param_count = 4,
		defaults = { amount = 0.66, param1 = 0.18, param2 = 0.64, param3 = 0.74, param4 = 0.52 },
	},
	{
		id = "haas_widen",
		engine = "haas",
		label = "haas widen",
		params = { "time", "spread", "tilt", "tone" },
		param_count = 4,
		defaults = { amount = 0.48, param1 = 0.42, param2 = 0.74, param3 = 0.5, param4 = 0.78 },
	},
	{
		id = "mono_lift",
		engine = "haas",
		label = "mono lift",
		params = { "time", "spread", "tilt", "tone" },
		param_count = 4,
		defaults = { amount = 0.58, param1 = 0.24, param2 = 0.9, param3 = 0.36, param4 = 0.64 },
	},
	{
		id = "tape_sat",
		engine = "tape_sat",
		label = "tape sat",
		params = { "drive", "bias", "mix", "tone" },
		param_count = 4,
		defaults = { amount = 0.52, param1 = 0.38, param2 = 0.24, param3 = 0.58, param4 = 0.46 },
	},
	{
		id = "warm_glue",
		engine = "tape_sat",
		label = "warm glue",
		params = { "drive", "bias", "mix", "tone" },
		param_count = 4,
		defaults = { amount = 0.68, param1 = 0.56, param2 = 0.18, param3 = 0.74, param4 = 0.34 },
	},
	{
		id = "transient_tame",
		engine = "transient",
		label = "transient tame",
		params = { "attack", "sustain", "mix", "tone" },
		param_count = 4,
		defaults = { amount = 0.58, param1 = 0.72, param2 = 0.22, param3 = 0.7, param4 = 0.58 },
	},
	{
		id = "sustain_bloom",
		engine = "transient",
		label = "sustain bloom",
		params = { "attack", "sustain", "mix", "tone" },
		param_count = 4,
		defaults = { amount = 0.72, param1 = 0.24, param2 = 0.82, param3 = 0.78, param4 = 0.52 },
	},
	{
		id = "tri_clip",
		engine = "multiclip",
		label = "tri clip",
		params = { "drive", "tilt", "mix", "tone" },
		param_count = 4,
		defaults = { amount = 0.62, param1 = 0.52, param2 = 0.5, param3 = 0.68, param4 = 0.44 },
	},
	{
		id = "band_burn",
		engine = "multiclip",
		label = "band burn",
		params = { "drive", "tilt", "mix", "tone" },
		param_count = 4,
		defaults = { amount = 0.78, param1 = 0.74, param2 = 0.66, param3 = 0.84, param4 = 0.28 },
	},
	{
		id = "tremolo",
		engine = "tremolo",
		label = "tremolo",
		params = { "rate", "depth", "shape", "bias" },
		param_count = 4,
		defaults = { amount = 0.58, param1 = 0.24, param2 = 0.72, param3 = 0.0, param4 = 0.5 },
	},
	{
		id = "gate_chop",
		engine = "tremolo",
		label = "gate chop",
		params = { "rate", "depth", "shape", "bias" },
		param_count = 4,
		defaults = { amount = 0.74, param1 = 0.36, param2 = 0.92, param3 = 1.0, param4 = 0.38 },
	},
	{
		id = "bit_crush",
		engine = "crusher",
		label = "bit crush",
		params = { "rate", "bits", "mix", "tone" },
		param_count = 4,
		defaults = { amount = 0.6, param1 = 0.46, param2 = 0.42, param3 = 0.55, param4 = 0.42 },
	},
	{
		id = "data_melt",
		engine = "crusher",
		label = "data melt",
		params = { "rate", "bits", "mix", "tone" },
		param_count = 4,
		defaults = { amount = 0.78, param1 = 0.18, param2 = 0.22, param3 = 0.84, param4 = 0.24 },
	},
	{
		id = "freq_shift",
		engine = "freq_shift",
		label = "freq shift",
		params = { "shift", "spread", "mix", "tone" },
		param_count = 4,
		defaults = { amount = 0.46, param1 = 0.22, param2 = 0.18, param3 = 0.55, param4 = 0.62 },
	},
	{
		id = "robot_drift",
		engine = "freq_shift",
		label = "robot drift",
		params = { "shift", "spread", "mix", "tone" },
		param_count = 4,
		defaults = { amount = 0.72, param1 = 0.58, param2 = 0.34, param3 = 0.82, param4 = 0.36 },
	},
	{
		id = "grain_freeze",
		engine = "granular",
		label = "grain freeze",
		params = { "density", "size", "scatter", "tone" },
		param_count = 4,
		defaults = { amount = 0.92, param1 = 0.18, param2 = 0.78, param3 = 0.08, param4 = 0.46 },
	},
	{
		id = "grain_scatter",
		engine = "granular",
		label = "grain scatter",
		params = { "density", "size", "scatter", "tone" },
		param_count = 4,
		defaults = { amount = 1.0, param1 = 0.82, param2 = 0.22, param3 = 0.92, param4 = 0.34 },
	},
	{
		id = "comb_drift",
		engine = "mod",
		label = "comb drift",
		params = { "rate", "depth", "type", "stages" },
		param_count = 4,
		defaults = { amount = 0.48, param1 = 0.24, param2 = 0.35, param3 = 1.0, param4 = 0.72 },
	},
	{
		id = "freeze_haze",
		engine = "delay",
		label = "freeze haze",
		params = { "time", "feedback", "freeze", "tone" },
		param_count = 4,
		defaults = { amount = 0.58, param1 = 0.22, param2 = 0.78, param3 = 1.0, param4 = 0.36 },
	},
	{
		id = "dub_bloom",
		engine = "delay",
		label = "dub bloom",
		params = { "time", "feedback", "freeze", "tone" },
		param_count = 4,
		defaults = { amount = 0.6, param1 = 0.48, param2 = 0.68, param3 = 0.25, param4 = 0.42 },
	},
	{
		id = "glass_bite",
		engine = "texture",
		label = "glass bite",
		params = { "color", "damage", "type", "motion" },
		param_count = 4,
		defaults = { amount = 0.5, param1 = 0.82, param2 = 0.34, param3 = 1.0, param4 = 0.18 },
	},
	{
		id = "pressure_drive",
		engine = "eq",
		label = "pressure drive",
		params = { "freq", "gain", "q", "style" },
		param_count = 4,
		defaults = { amount = 0.54, param1 = 0.38, param2 = 0.7, param3 = 0.55, param4 = 0.0 },
	},
}

local Effects = {
	definitions = effect_definitions,
	order = {},
	labels = {},
	params = {},
	param_counts = {},
	default_values = {},
	index_map = {},
	engine_map = {},

	-- Filter presets that share cutoff/res/slope when switching within the group.
	linked_filter_modes = {
		low_pass = true,
		band_pass = true,
		high_pass = true,
	},

	-- Maps old engine-name strings saved in v1 banks to current effect IDs.
	legacy_effect_map = {
		thru = "thru",
		filter = "washed_hall",
		eq = "pressure_drive",
		mod = "comb_drift",
		space = "washed_hall",
		texture = "broken_tape",
		delay = "dub_bloom",
	},

	-- Engine-side effect index used by the SC SynthDef SelectX.
	-- Keep this aligned with docs/effect-engine-map.md and the index order
	-- documented in lib/Engine_Fadddddddder.sc.
	engine_effect_index = {
		thru = 0,
		filter = 1,
		eq = 2,
		mod = 3,
		space = 4,
		texture = 5,
		delay = 6,
		resonator = 7,
		fold_filter = 8,
		formant = 9,
		tremolo = 10,
		crusher = 11,
		freq_shift = 12,
		granular = 13,
		plate = 14,
		early = 15,
		haas = 16,
		tape_sat = 17,
		transient = 18,
		multiclip = 19,
	},
}

for i, def in ipairs(effect_definitions) do
	Effects.order[i] = def.id
	Effects.labels[def.id] = def.label
	Effects.params[def.id] = def.params
	Effects.param_counts[def.id] = def.param_count
	Effects.default_values[def.id] = def.defaults
	Effects.index_map[def.id] = i
	Effects.engine_map[def.id] = def.engine
end

return Effects
